# fly.toml app configuration file generated for ibx-sanic-app on 2023-08-29T01:43:08+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ibx-sanic-app"
primary_region = "hkg"

[build]
  builder = "paketobuildpacks/builder:base"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
